"de_dust2_old"
{
		"name" "de_dust2_old"
		"t_arms" "models/weapons/t_arms_leet.mdl"
		"ct_arms" "models/weapons/ct_arms_sas.mdl"

"t_models"
{
		 "tm_leet_variantA"""
		 "tm_leet_variantB"""
		 "tm_leet_variantC"""
		 "tm_leet_variantD"""
		 "tm_leet_variantE"""
}

"ct_models"
{
		"ctm_sas"""
		"ctm_sas_variantA"""
		"ctm_sas_variantB"""
		"ctm_sas_variantC"""
		"ctm_sas_variantD"""
		"ctm_sas_variantE"""
}
}